version: "2"
checks:
  argument-count:
    config:
      threshold: 10
  complex-logic:
    config:
      threshold: 50
  file-lines:
    config:
      threshold: 1500
  method-complexity:
    config:
      threshold: 50
  method-count:
    config:
      threshold: 100
  method-lines:
    config:
      threshold: 150
  nested-control-flow:
    config:
      threshold: 6
  return-statements:
    config:
      threshold: 6
  similar-code:
    enabled: false
  identical-code:
    enabled: false
exclude_patterns:
  - "**/test/"
  - "**/androidTest/"
  - "libtest/"
